# Generated by Django 4.1.1 on 2022-10-01 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
    ]
